os: linux
dist: xenial
language: bash
script: make test
stages:
- test
deploy:
  provider: releases
  api_key:
    secure: szOlwUxLx2zZnDRm+XJshNGkV1JA78qqxPHNkikM82pBcCqpXyBVxUde4ikyUcq4m2RaqBMOqWSL1ki5qHg+Y2qR0q55DIkxCCH0JBcqRFlg9awlbPCvm//nj+a+BP51SySgD3MozmkqgjKz0fgMalL54ZHRgh7xFBLxLg0mjw15U/kjz4L/XoDKlCIeyIyyLMxzgqO7HFecpkS1G6JV+Hkmdk+ExAO5eeKdme6baMcXZJ28VsKCu9arIm/Rccadpwsng6neHM4sYo4Nd6raoFKoVcD646NZEU/f9xs3SFLEsSrziR3B6QcCApK0E9LxjOCUomwVk8xFXrfjD+zq9AwGtwmxmALnzcozzAQ5sB72nriF0gyWQcOaoxJnS47mVbONbU89TAxuyzg5tmdDaZ5Tu31FR6R9W1f4O9EBLzFu9rgMsM6zGLruCc2lMk0y5UduSbBmfR0cJvbNHuuc4n1F6dbBoDU9c9cnKfG6Etg4Em+B/VECgHUXieSUwL0k6yKcI9vluN9FTPgwV7uVVn+DUFGBAyPOgMbK91QiD249Q9owg0mnTfaDwAAptDCDP/5F1niHPEC1e2f00rdrnVDt8ohS1gypTKF2zWhIbj8fMmEAkzhVT0kmcUI6jZO4Z9VaLlY7ZFpVQzmMa6plWZKIswuX/jFu+/Ug/A/FUWc=
  file: masternode.sh
  on:
    repo: AltcoinBaggins/veles-installer
jobs:
  include:
    - stage: test
      name: 'Ubuntu [xenial]  [GOAL: install, update]'
      script:
         - travis_retry sudo make test_install && sudo make test_install
    - stage: test
      name: 'Linux Mint [latest]  [GOAL: install]'
      script:
         - travis_retry sudo docker run --rm=true -v `pwd`:/veles-masternode:rw vcatechnology/linux-mint /bin/bash -c "apt-get update ; apt-get install -q -y wget curl make procps python ; cd /veles-masternode/; make docker_test_install"
    - stage: test
      name: 'Debian [stable]  [GOAL: install]'
      script:
         - travis_retry sudo docker run --rm=true -v `pwd`:/veles-masternode:rw debian:latest /bin/bash -c "apt-get update ; apt-get install -q -y wget curl make procps python net-tools ; cd /veles-masternode/; make docker_test_install"
    - stage: test
      name: 'CentOS [latest]  [GOAL: install, update]'
      script:
         - travis_retry sudo docker run --rm=true -v `pwd`:/veles-masternode:rw centos:latest /bin/bash -c "yum -y install make wget curl python iproute ; cd /veles-masternode/; make docker_test_install && make test_install"
    - stage: test
      name: 'Gentoo [stage3]  [GOAL: install]'
      script:
         - travis_retry sudo docker run --rm=true -v `pwd`:/veles-masternode:rw gentoo/stage3-amd64 /bin/bash -c "cd /veles-masternode/; make docker_test_install"
    - stage: test
      name: '[ experimental ] Fedora [latest]  [GOAL: install]'
      script:
         - travis_retry sudo docker run --rm=true -v `pwd`:/veles-masternode:rw fedora:latest /bin/bash -c "yum -y install make wget curl procps python iproute ; cd /veles-masternode/; make docker_test_install"
    #- stage: test
    #  name: '[ experimental ] OpenSUSE [leap]  [GOAL: install]'
    #  script:
    #     - travis_retry sudo docker run --rm=true -v `pwd`:/veles-masternode:rw opensuse/leap /bin/bash -c "zypper --non-interactive install make wget tar gzip python curl ; groupadd mail ; cd /veles-masternode/; make docker_test_install"




