os: linux
dist: xenial
language: bash
script: make test
stages:
  - test
jobs:
  include:
    - stage: test
      name: '[experimental] Fedora [latest]  [GOAL: install, update]'
      script:
         - travis_retry sudo docker run --rm=true -v `pwd`:/veles-masternode:rw fedora:latest /bin/bash -c "yum -y install make wget procps python ; cd /veles-masternode/; make test_as_root"
    - stage: test
      name: '[experimental] Linux Mint [latest]  [GOAL: install, update]'
      script:
         - travis_retry sudo docker run --rm=true -v `pwd`:/veles-masternode:rw vcatechnology/linux-mint /bin/bash -c "apt-get update ; apt-get install -q -y wget make procps python ; cd /veles-masternode/; make test_as_root"
    - stage: test
      name: 'Ubuntu [xenial]  [GOAL: install, update]'
      script:
         - travis_retry make test
    - stage: test
      name: 'Debian [stable]  [GOAL: install, update]'
      script:
         - travis_retry sudo docker run --rm=true -v `pwd`:/veles-masternode:rw debian:latest /bin/bash -c "apt-get update ; apt-get install -q -y wget make procps python ; cd /veles-masternode/; make test_as_root"
    - stage: test
      name: 'CentOS [latest]  [GOAL: install, update]'
      script:
         - travis_retry sudo docker run --rm=true -v `pwd`:/veles-masternode:rw centos:latest /bin/bash -c "yum -y install make wget python ; cd /veles-masternode/; make test_as_root"
    - stage: test
      name: 'Gentoo [stage3]  [GOAL: install, update]'
      script:
         - travis_retry sudo docker run --rm=true -v `pwd`:/veles-masternode:rw gentoo/stage3-amd64 /bin/bash -c "cd /veles-masternode/; make test_as_root"




